name: CI - Dev Branch

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gs]
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
      
      - name: Authenticate to Google Cloud
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project mlops-ga-474200
      
      - name: Pull Data and Model from DVC
        run: dvc pull
        
      - name: Run Tests
        run: pytest -v --maxfail=1 --disable-warnings

      - name: Sanity Report via CML
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## ✅ Pytest Results" > report.md
          pytest --maxfail=1 --disable-warnings -q >> report.md
          cml comment create report.md
