name: CI - Main Branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gs]
          
      # ✅ Use official GCP auth action instead of manual install
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mlops-ga-474200
      
      - name: Pull Data and Model from DVC
        run: dvc pull
        
      - name: Run Tests
        run: pytest -v --maxfail=1 --disable-warnings
        
      - name: Install CML
        run: |
          npm install -g @dvcorg/cml
          
      - name: Sanity Report via CML
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## ✅ Pytest Results" > report.md
          pytest --maxfail=1 --disable-warnings -q >> report.md
          cml comment create report.md
